# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef0e54b7221642c65bc27fb02b9af68319e6e0aa89aedae6f1010164b42a2f4e12683d7b94d1d9bc16a2390b3905bcc5d514ba213a4cf870540373098cabecd

test:
  secret_key_base: 3cf0b684985ea348f352700ab8317f25f61e80c30d7451f1dad14d40df9253f1316104686c63a18efd4de6b2836d8621b2da0537bac18282331f7dc942f35ee1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
